# Generated by Django 5.2.7 on 2025-10-30 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_options'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.ForeignKey(blank=True, help_text='Категория услуг, в которой специализируется мастер', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicecategory', verbose_name='Специализация'),
        ),
    ]
