# Generated by Django 5.2.7 on 2025-11-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор салона'), ('staff', 'Мастер'), ('client', 'Клиент')], default='client', max_length=16, verbose_name='Роль'),
        ),
    ]
