# Generated by Django 5.2.7 on 2025-10-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_slug_alter_servicecategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
